export function renderHelp(): string {
  return [
    "Whyline — answer \"Why does this line exist?\"",
    "",
    "Usage:",
    "  whyline <file>:<line>",
    "  whyline <file>:<start>-<end>",
    "  whyline [--details] --symbol <selector> <file>",
    "  whyline --help",
    "  whyline --version",
    "",
    "Options:",
    "  --details  show bounded evidence and diagnostic details",
    "  --symbol   resolve one exact TypeScript/JavaScript-family symbol in a file",
    "  --help     show this help",
    "  --version  show the installed Whyline version",
    "",
    "Whyline combines:",
    "  • Git textual attribution",
    "  • exact Git-visible ancestry",
    "  • bounded transformed declaration correspondence",
    "  • local Codex history correlation",
    "  • current worktree-change correlation",
    "",
    "It distinguishes observed facts, deterministic derivations, and conservative inference.",
    "It does not claim authorship, causation, or an authorship oracle.",
    "Uncommitted targets are reported as worktree changes; they are not attributed to an agent.",
    "",
    "Requirements:",
    "  Node.js 24+ and Git 2.36+",
    "  Supported: Linux and macOS",
    "  Windows: unsupported and untested for v0.1.0",
    "",
    "Exit codes:",
    "  0  analysis completed, including Git-only, ambiguous, and uncommitted results",
    "  2  invalid input or unsupported target",
    "  3  operational failure",
  ].join("\n");
}
